# Generated by Django 4.2.1 on 2023-11-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0108_labour_support_land_id_n0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='APPROVED_BY',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='AVERAGE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='BATCH_CODE',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='Broken',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='DATE',
            field=models.DateField(blank=True, null=True, verbose_name='Current Date'),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='DATE_OF_REPORT',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Report'),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='DATE_OF_SAMPLING',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Sampling'),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='DECISION',
            field=models.CharField(blank=True, choices=[('', 'What was the decision made?'), ('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='Final_Sample_Weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='Initial_Sample_Weight',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='Insect_Damaged',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='Mould',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='Quantity_of_Bags',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='Quantity_of_Sample',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='READING_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='READING_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='READING_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='SIGNED_BY_QUALITY_ASSURANCE_OFFICER',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='STATION',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='TEST_PERFORMED_BY',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='Total_Weight',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='APPROVED_BY',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='AVERAGE',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='BATCH_CODE',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='Broken',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='DATE',
            field=models.DateField(blank=True, null=True, verbose_name='Current Date'),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='DATE_OF_REPORT',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Report'),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='DATE_OF_SAMPLING',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Sampling'),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='DECISION',
            field=models.CharField(blank=True, choices=[('', 'What was the decision made?'), ('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='Final_Sample_Weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='Initial_Sample_Weight',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='Insect_Damaged',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='Mould',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='READING_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='READING_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='READING_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='SIGNED_BY_QUALITY_ASSURANCE_OFFICER',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='STATION',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='TEST_PERFORMED_BY',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='Total_Quantity_of_Bags_in_Non_Compliance',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='Total_Weight_of_Nutmeg_in_Non_Compliance',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
